version: 'latest'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    ports:
    - 8082:8082
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  db:
    volumes:
      - C:/Users/prsok/volumes/databases/postgresql/graphql:/var/lib/postgresql/data
    image:
      postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5431:5432
