// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID          string  `json:"id"`
	Brand       string  `json:"brand"`
	Model       string  `json:"model"`
	Year        int     `json:"year"`
	Price       float64 `json:"price"`
	Mileage     int     `json:"mileage"`
	Description string  `json:"description"`
}

type CarInput struct {
	Brand       string  `json:"brand"`
	Model       string  `json:"model"`
	Year        int     `json:"year"`
	Price       float64 `json:"price"`
	Mileage     int     `json:"mileage"`
	Description string  `json:"description"`
}

type Mutation struct {
}

type Query struct {
}
