// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID          string  `json:"id"`
	User        *User   `json:"user"`
	Brand       string  `json:"brand"`
	Model       string  `json:"model"`
	Year        int     `json:"year"`
	Price       float64 `json:"price"`
	Mileage     int     `json:"mileage"`
	Description string  `json:"description"`
}

type CarInput struct {
	UserID      string  `json:"userId"`
	Brand       string  `json:"brand"`
	Model       string  `json:"model"`
	Year        int     `json:"year"`
	Price       float64 `json:"price"`
	Mileage     int     `json:"mileage"`
	Description string  `json:"description"`
}

type Login struct {
	SessionID string `json:"sessionID"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Password string `json:"password"`
}
